[package]
name = "pneumatic_beacon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pneumatic_core = { git = "https://github.com/garrettkolson/pneumatic_core.git" }
dashmap = "5.5.3"